/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include "include/cn_ylbkoo_sophia_SophiaInterface.h"

#include "sophia.h"

#define JNI_GetStringChars(env, string) ((*env)->GetStringUTFChars(env, string, JNI_FALSE))
#define JNI_ReleaseChars(env, string, jni_char) (*env)->ReleaseStringUTFChars(env, string, jni_char);

/* Header for class cn_ylbkoo_sophia_SophiaInterface */

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_env
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1env
  (JNIEnv * env, jobject obj)
  {
    return (jlong)sp_env();
  }

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_document
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1document
  (JNIEnv * env, jobject obj, jlong ptr)
  {
    void *object = (void *) ptr;
    return (jlong)sp_document(object);
  }

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_setstring
 * Signature: (JLjava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1setstring
  (JNIEnv * env, jobject obj, jlong db_env, jstring key, jstring value, jint size)
  {
    const char* key_char = JNI_GetStringChars(env, key);
    const void* value_char = JNI_GetStringChars(env, value);

    jint rec = sp_setstring((void *)db_env, key_char, value_char, size);

    JNI_ReleaseChars(env, key, key_char);
    JNI_ReleaseChars(env, value, value_char);

    return rec;
  }

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_setint
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1setint
  (JNIEnv *env, jobject obj, jlong ptr, jstring path, jlong value)
  {
    const char* path_char = JNI_GetStringChars(env, path);
    jlong rec = (jlong) sp_setint((void *) ptr, path_char, (long) value);

    JNI_ReleaseChars(env, path, path_char);

    return rec;
  }

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_getobject
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1getobject
  (JNIEnv *env, jobject obj, jlong ptr, jstring path)
{
    const char* path_char = JNI_GetStringChars(env, path);
    jlong rec = (jlong) sp_getobject((void *) ptr, path_char);

    JNI_ReleaseChars(env, path, path_char);

    return rec;
}

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_getstring
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1getstring
  (JNIEnv *env, jobject obj, jlong db_object, jstring path, jint size)
  {
    const char* path_char = JNI_GetStringChars(env, path);
    int * size_p = (int *) size;
    jlong rec = (jlong) sp_getstring((void *) db_object, path_char, size_p);

    JNI_ReleaseChars(env, path, path_char);

    return rec;
  }

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_getint
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1getint
  (JNIEnv *env, jobject obj, jlong db_object, jstring path)
  {
    const char* path_char = JNI_GetStringChars(env, path);
    jlong rec = (jlong) sp_getint((void *) db_object, path_char);

    JNI_ReleaseChars(env, path, path_char);

    return rec;
  }

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_open
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1open
  (JNIEnv *env, jobject obj, jlong db_env)
  {
    return (jint) sp_open((void *) db_env);
  }

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1destroy
  (JNIEnv *env, jobject obj, jlong db_object)
  {
    return (jint) sp_destroy((void *) db_object);
  }

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_set
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1set
  (JNIEnv *env, jobject obj, jlong database, jlong document)
  {
    return (jint) sp_set((void *) database, (void *) document);
  }

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_upsert
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1upsert
  (JNIEnv *env, jobject obj, jlong database, jlong document)
  {
    return (jint) sp_upsert((void *) database, (void *) document);
  }

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_delete
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1delete
  (JNIEnv *env, jobject obj, jlong database, jlong document)
  {
    return (jint) sp_delete((void *)database, (void *)document);
  }

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_get
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1get
  (JNIEnv *env, jobject obj, jlong database, jlong document)
  {
    return (jlong) sp_get((void *)database, (void *)document);
  }

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_cursor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1cursor
  (JNIEnv *env, jobject obj, jlong db_env)
  {
    return (jlong) sp_cursor((void *)db_env);
  }

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_begin
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1begin
  (JNIEnv *env, jobject obj, jlong db_env)
  {
    return (jlong) sp_begin((void *)db_env);
  }

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_commit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1commit
  (JNIEnv *env, jobject obj, jlong transaction)
  {
    return (jint) sp_commit((void *) transaction);
  }
