/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ylbkoo_sophia_SophiaInterface */

#ifndef _Included_cn_ylbkoo_sophia_SophiaInterface
#define _Included_cn_ylbkoo_sophia_SophiaInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_env
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1env
  (JNIEnv *, jobject);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_document
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1document
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_setstring
 * Signature: (JLjava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1setstring
  (JNIEnv *, jobject, jlong, jstring, jstring, jint);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_setint
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1setint
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_getobject
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1getobject
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_getstring
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1getstring
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_getint
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1getint
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_open
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1open
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_set
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1set
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_upsert
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1upsert
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_delete
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1delete
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_get
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1get
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_cursor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1cursor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_begin
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1begin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cn_ylbkoo_sophia_SophiaInterface
 * Method:    sp_commit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_ylbkoo_sophia_SophiaInterface_sp_1commit
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
